/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;

import BEAN.Beanlogin;
import CONNECT.Myconnect;
import DAO.DAOlogin;
import Utilitarios.Tablecliente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author luizb
 */
public class FrmCadusuario extends javax.swing.JInternalFrame {
private  Connection conecta;
    /**
     * Creates new form FrmCadusuario
     */
    public FrmCadusuario() {
        initComponents();
         this.conecta=new Myconnect().conecta();
         PreencherTabela("SELECT * from login order by idlogin");
         //this.setLocationRelativeTo(null);
         this.cadfun();
    }
 public void cadfun() {
    try {
         String cmdsql;
            cmdsql = "select * from login ";
            PreparedStatement stmt = conecta.prepareStatement(cmdsql);
             ResultSet rs =stmt.executeQuery();            
             
             while(rs.next()){
               jComboperfil2.removeAllItems();
               jComboperfil2.addItem("Administrador");
                jComboperfil2.addItem("usuario");
           }
    } catch (Exception e) {
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboperfil2 = new javax.swing.JComboBox<>();
        codigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelafun = new javax.swing.JTable();
        cadastrar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela Cadastro de Usuário");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Usuário:");

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Senha:");

        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Perfil:");

        jComboperfil2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Perfil" }));
        jComboperfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboperfil2ActionPerformed(evt);
            }
        });

        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setText("Código:");

        txtcodigo.setEditable(false);
        txtcodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcodigoMouseClicked(evt);
            }
        });
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboperfil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboperfil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );

        tabelafun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelafun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelafunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelafun);

        cadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user24.png"))); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        deletar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cancel.png"))); // NOI18N
        deletar.setText("Deletar");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pencil.png"))); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        limpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/wiping-swipe-for-floors.png"))); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        Atualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh-button.png"))); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        voltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back.png"))); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cadastrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(deletar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(limpar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Atualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Atualizar)
                        .addComponent(voltar)
                        .addComponent(limpar)
                        .addComponent(editar)
                        .addComponent(deletar)
                        .addComponent(cadastrar))
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void jComboperfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboperfil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboperfil2ActionPerformed

    private void txtcodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcodigoMouseClicked

    }//GEN-LAST:event_txtcodigoMouseClicked

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed

    }//GEN-LAST:event_txtcodigoActionPerformed

    private void tabelafunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafunMouseClicked
        txtcodigo.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(),0).toString());
        txtusuario.setText( tabelafun.getValueAt(tabelafun.getSelectedRow(),1).toString());
        txtsenha.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(),2).toString());
        jComboperfil2.setSelectedItem(tabelafun.getValueAt(tabelafun.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tabelafunMouseClicked

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed

        try {
            Beanlogin obj = new Beanlogin();
            //obj.setIdlogin(Integer.valueOf(txtcodigo.getText()));
            obj.setUsuario(txtusuario.getText());
            obj.setSenha( txtsenha.getText());
            obj.setPerfil((String)jComboperfil2.getSelectedItem());
            DAOlogin dao = new DAOlogin();
            dao.cadastrarusuario(obj);
            JOptionPane.showMessageDialog(null, "Cadastro Realizado com sucesso!");
            PreencherTabela("SELECT * from login order by idlogin");
            //PreencherTabela("select * from cliente order by idcliente");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO AO CADASTRAR:"+ erro);

        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        try {
            Beanlogin obj = new Beanlogin();
            obj.setIdlogin(Integer.parseInt(txtcodigo.getText()));
            DAOlogin dao = new DAOlogin();
            dao.deletaruser(obj);
            JOptionPane.showMessageDialog(null, "Cadastro Realizado com sucesso!");
            PreencherTabela("SELECT * from login order by idlogin");
            //PreencherTabela("select * from cliente order by idcliente");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO AO CADASTRAR:"+ erro);

        }
    }//GEN-LAST:event_deletarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed

        try {
            Beanlogin obj = new Beanlogin();
            obj.setIdlogin(Integer.valueOf(txtcodigo.getText()));
            obj.setUsuario(txtusuario.getText());
            obj.setSenha( txtsenha.getText());
            obj.setPerfil((String)jComboperfil2.getSelectedItem());
            DAOlogin dao = new DAOlogin();
            dao.alterarusuario(obj);
            JOptionPane.showMessageDialog(null, "Cadastro Alterado com sucesso!");
            PreencherTabela("SELECT * from login order by idlogin");
            //PreencherTabela("select * from cliente order by idcliente");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO AO CADASTRAR:"+ erro);

        }
    }//GEN-LAST:event_editarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        txtcodigo.setText("");
        txtusuario.setText("");
        txtsenha.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        PreencherTabela("select * from login order by idlogin");
    }//GEN-LAST:event_AtualizarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed
public void PreencherTabela(String cmdsql){
    
    
    ArrayList dados = new ArrayList();
    String[] Colunas = new String[]{
        "Código",
        "Usuário",
        "Senha",
        "Perfil",
    };
    try {
       PreparedStatement stmt = conecta.prepareStatement(cmdsql);
        ResultSet rs = stmt.executeQuery();
       while(rs.next()) {
         dados.add(new Object[]{
             rs.getInt("idlogin"),
             rs.getString("usuario"),
             rs.getString("senha"),
             rs.getString("perfil"),
         });
       
        }
       rs.first();
       // stmt.execute();
      // 
     
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Erro ao preencher a ArrayList ERRO:"+ e);
    }
    
    Tablecliente modelo = new Tablecliente(dados, Colunas);
    
    tabelafun.setModel(modelo);
    tabelafun.getColumnModel().getColumn(0).setPreferredWidth(308);//id
    tabelafun.getColumnModel().getColumn(0).setResizable(false);//id
    tabelafun.getColumnModel().getColumn(1).setPreferredWidth(300);//nome
    tabelafun.getColumnModel().getColumn(1).setResizable(false);//nome
    tabelafun.getColumnModel().getColumn(2).setPreferredWidth(360);//nasc
    tabelafun.getColumnModel().getColumn(2).setResizable(false);//nasc
    tabelafun.getColumnModel().getColumn(3).setPreferredWidth(370);//perfil
    tabelafun.getColumnModel().getColumn(3).setResizable(false);//perfil
    //tabelafun.getColumnModel().getColumn(4).setPreferredWidth(100);//rg
    tabelafun.getTableHeader().setResizingAllowed(false);
    tabelafun.setAutoResizeMode(tabelafun.AUTO_RESIZE_ALL_COLUMNS);
    tabelafun.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
   
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel codigo;
    private javax.swing.JButton deletar;
    private javax.swing.JButton editar;
    private javax.swing.JComboBox<String> jComboperfil2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JTable tabelafun;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtsenha;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
