/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;
import BEAN.Beanlogin;
import CONNECT.Myconnect;
import DAO.DAOlogin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author luiz.barros
 */
public class Frmlogin extends javax.swing.JFrame {
private  Connection conecta;
    /**
     * Creates new form login
     */
    public Frmlogin() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.conecta=new Myconnect().conecta();
         this.status();
         this.cadfun();
        
    }

    public void status(){
        if(conecta != null){
            statusdb.setIcon(new ImageIcon(getClass().getResource("/IMG/database_on.png")));
        }else{
             statusdb.setIcon(new ImageIcon(getClass().getResource("/IMG/database_off.png")));
        }
    }
    public void cadfun() {
    try {
         String cmdsql;
            cmdsql = "select * from login ";
            PreparedStatement stmt = conecta.prepareStatement(cmdsql);
             ResultSet rs =stmt.executeQuery();            
             
             while(rs.next()){
               jComboBox1.removeAllItems();
               jComboBox1.addItem("Administrador");
                jComboBox1.addItem("usuario");
           }
    } catch (Exception e) {
    }
}
    public void pegaiditem(){
     try {

         String cmdsql;
         String prodselect = txtusuario.getText();
           cmdsql = "SELECT perfil " +"FROM login " +"WHERE " +"(usuario ='" + prodselect + "')"; 
//""'"+jComboBoxCliente.getSelectedItem().toString()+"'";
            //cmdsql = "select * from produto order by idproduto";
            PreparedStatement stmt = conecta.prepareStatement(cmdsql);
             ResultSet rs =stmt.executeQuery();            
            //rs.first();
            while(rs.next()){
            String perfil = rs.getString(1);
             jComboBox1.setSelectedItem(perfil);
            }
              /*if( rs.getString("produto").equals(jComboBoxCliente.getSelectedItem().toString())){
                 // while(rs.next()){
               txtcodigoprod.setText(rs.getString("idproduto")); 
                  //}
           }else{
                   JOptionPane.showMessageDialog(rootPane,"Erro ao Pegar ID");
              }
              */
              
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane,"Erro ao Pegar ID"+e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sair = new javax.swing.JButton();
        btbuscar = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        txtusuario = new javax.swing.JTextField();
        labelusuario = new javax.swing.JLabel();
        labelusuario1 = new javax.swing.JLabel();
        statusdb = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        labelusuario2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        sair.setBackground(new java.awt.Color(204, 0, 0));
        sair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        btbuscar.setBackground(new java.awt.Color(51, 255, 51));
        btbuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btbuscar.setText("Entrar");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        labelusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelusuario.setText("Usuário:");

        labelusuario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelusuario1.setText("Senha:");

        statusdb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/database_off.png"))); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setEnabled(false);

        labelusuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelusuario2.setText("Perfil:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 210, Short.MAX_VALUE)
                            .addComponent(txtsenha)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addComponent(sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statusdb))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(statusdb)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelusuario)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btbuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
       this.pegaiditem();
        try {
              Beanlogin obj = new Beanlogin();
            obj.setUsuario(txtusuario.getText());
            obj.setSenha(txtsenha.getText()); 
            obj.setPerfil(jComboBox1.getSelectedItem().toString()); 
            DAOlogin dao = new DAOlogin();
              if( dao.fazerlogin(obj)){
                  
      if(obj.getPerfil().equals("Administrador")){
            FrmPrincipal telacliente = new FrmPrincipal(txtusuario.getText(),jComboBox1.getSelectedItem().toString());
            telacliente.setVisible(true);
                this.dispose();
                    JOptionPane.showMessageDialog(rootPane,"Seja Bem-Vindo "+txtusuario.getText()+"");
      }
            
        
         
     else if(obj.getPerfil().equals("usuario")){
     FrmPrincipal telacliente = new FrmPrincipal(txtusuario.getText(),jComboBox1.getSelectedItem().toString());
     telacliente.setVisible(true);
     this.dispose();
     JOptionPane.showMessageDialog(rootPane,"Seja Bem-Vindo "+txtusuario.getText()+"");
      }
              }
      else{
       //exibe uma mensagem para o usuario.
       JOptionPane.showMessageDialog(null,"Dados incorretos!");
  }
           }
           
      //abra a tela de cadastro
     
         catch (Exception e) {
            
        }

    }//GEN-LAST:event_btbuscarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbuscar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelusuario;
    private javax.swing.JLabel labelusuario1;
    private javax.swing.JLabel labelusuario2;
    private javax.swing.JButton sair;
    private javax.swing.JLabel statusdb;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
