/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;

import BEAN.BEANproduto;
import CONNECT.Myconnect;
import DAO.DAOproduto;
import Utilitarios.Tablecliente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author luizb
 */
public class Frmprodutos extends javax.swing.JInternalFrame {
private  Connection conecta;
    /**
     * Creates new form Frmprodutos
     */
    public Frmprodutos() {
        initComponents();
         this.conecta=new Myconnect().conecta();
         PreencherTabela("select * from produto order by idproduto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtproduto = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        codigo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtbuscarproduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelafun = new javax.swing.JTable();
        cadastrar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastra Produto"));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Produto:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Valor:");

        txtproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodutoActionPerformed(evt);
            }
        });

        txtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorActionPerformed(evt);
            }
        });

        txtcodigo.setEditable(false);
        txtcodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcodigoMouseClicked(evt);
            }
        });
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setText("Código:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Produto"));

        txtbuscarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarprodutoActionPerformed(evt);
            }
        });
        txtbuscarproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarprodutoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Produto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscarproduto)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtbuscarproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tabelafun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelafun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelafunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelafun);

        cadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user24.png"))); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        deletar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cancel.png"))); // NOI18N
        deletar.setText("Deletar");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pencil.png"))); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        limpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/wiping-swipe-for-floors.png"))); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        Atualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh-button.png"))); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        voltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back.png"))); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cadastrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deletar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(limpar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Atualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Atualizar)
                        .addComponent(voltar)
                        .addComponent(limpar)
                        .addComponent(editar)
                        .addComponent(deletar)
                        .addComponent(cadastrar))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodutoActionPerformed

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorActionPerformed

    private void txtcodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcodigoMouseClicked

    }//GEN-LAST:event_txtcodigoMouseClicked

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed

    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtbuscarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarprodutoActionPerformed

    }//GEN-LAST:event_txtbuscarprodutoActionPerformed

    private void txtbuscarprodutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarprodutoKeyReleased
        String nome = txtbuscarproduto.getText();
        if(nome.equals("")){
            //JOptionPane.showMessageDialog(this,"Digite Um Produto!");
            txtbuscarproduto.requestFocus();
            PreencherTabela("select * from produto order by idproduto");
        }
        else{
            PreencherTabela("SELECT * FROM produto WHERE produto LIKE '"+nome+ "%'");
        }

    }//GEN-LAST:event_txtbuscarprodutoKeyReleased

    private void tabelafunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafunMouseClicked
        txtcodigo.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(),0).toString());
        txtproduto.setText( tabelafun.getValueAt(tabelafun.getSelectedRow(),1).toString());
        txtvalor.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(),2).toString());
        // jComboperfil2.setSelectedItem(tabelafun.getValueAt(tabelafun.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tabelafunMouseClicked

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed

        try {
            BEANproduto obj = new BEANproduto();
            //obj.setIdlogin(Integer.valueOf(txtcodigo.getText()));
            obj.setProduto(txtproduto.getText());
            obj.setValor(txtvalor.getText());
            //obj.setPerfil((String)jComboperfil2.getSelectedItem());
            DAOproduto dao = new DAOproduto();
            dao.cadastrproduto(obj);
            JOptionPane.showMessageDialog(null, "Cadastro Realizado com sucesso!");
            PreencherTabela("SELECT * from produto order by idproduto");
            //PreencherTabela("select * from cliente order by idcliente");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO AO CADASTRAR:"+ erro);

        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        try {
            BEANproduto obj = new BEANproduto();
            obj.setIdproduto(Integer.parseInt(txtcodigo.getText()));
            DAOproduto dao = new DAOproduto();
            dao.deletaruser(obj);
            JOptionPane.showMessageDialog(null, "Cadastro Deletado com sucesso!");
            PreencherTabela("SELECT * from produto order by idproduto");
            //PreencherTabela("select * from cliente order by idcliente");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO AO CADASTRAR:"+ erro);

        }
    }//GEN-LAST:event_deletarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed

        try {
            BEANproduto obj = new BEANproduto();
            obj.setIdproduto(Integer.valueOf(txtcodigo.getText()));
            obj.setProduto(txtproduto.getText());
            obj.setValor(txtvalor.getText());
            //obj.setPerfil((String)jComboperfil2.getSelectedItem());
            DAOproduto dao = new DAOproduto();
            dao.alterarproduto(obj);
            JOptionPane.showMessageDialog(null, "Cadastro Alterado com sucesso!");
            PreencherTabela("SELECT * from produto order by idproduto");
            //PreencherTabela("select * from cliente order by idcliente");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO AO CADASTRAR:"+ erro);

        }
    }//GEN-LAST:event_editarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        txtcodigo.setText("");
        txtproduto.setText("");
        txtvalor.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        PreencherTabela("select * from produto order by idproduto");
    }//GEN-LAST:event_AtualizarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed
public void PreencherTabela(String cmdsql){
    
    
    ArrayList dados = new ArrayList();
    String[] Colunas = new String[]{
        "Código",
        "Produto",
        "Valor",
    };
    try {
       PreparedStatement stmt = conecta.prepareStatement(cmdsql);
        ResultSet rs = stmt.executeQuery();
       while(rs.next()) {
         dados.add(new Object[]{
             rs.getInt("idproduto"),
             rs.getString("produto"),
             rs.getString("valor"),
             });
       
        }
       rs.first();
       // stmt.execute();
      // 
     
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Erro ao preencher a ArrayList ERRO:"+ e);
    }
    
    Tablecliente modelo = new Tablecliente(dados, Colunas);
    
    tabelafun.setModel(modelo);
    tabelafun.getColumnModel().getColumn(0).setPreferredWidth(308);//id
    tabelafun.getColumnModel().getColumn(0).setResizable(false);//id
    tabelafun.getColumnModel().getColumn(1).setPreferredWidth(300);//nome
    tabelafun.getColumnModel().getColumn(1).setResizable(false);//nome
    tabelafun.getColumnModel().getColumn(2).setPreferredWidth(360);//nasc
    tabelafun.getColumnModel().getColumn(2).setResizable(false);//nasc
    tabelafun.getTableHeader().setResizingAllowed(false);
    tabelafun.setAutoResizeMode(tabelafun.AUTO_RESIZE_ALL_COLUMNS);
    tabelafun.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
   
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel codigo;
    private javax.swing.JButton deletar;
    private javax.swing.JButton editar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JTable tabelafun;
    private javax.swing.JTextField txtbuscarproduto;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtproduto;
    private javax.swing.JTextField txtvalor;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
