/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;
import BEAN.Beanlogin;
import java.awt.Desktop;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author luizb
 */
public class FrmPrincipal extends javax.swing.JFrame {
 private  Connection conecta;
    /**
     * Creates new form FrmPrincipall
     */
    public FrmPrincipal(String user,String perfil) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        labeluser.setText(user);
        labeperfil.setText(perfil);
        this.perfiladm();
        
    }
 FrmPrincipal() {
        initComponents();
       
    }
 public void perfiladm(){
      // String prodselect = labeluser.getText();
      if(labeperfil.getText().equals("Administrador")){
                
              menuproduto.setEnabled(true);
              menurelatoriovenda.setEnabled(true);
              menucaduser.setEnabled(true);
              relatorioentrega.setEnabled(true);
              cadusuario.setEnabled(true);

            }
            else{
                
            }
     
    /* try {
            String cmdsql;
         
            cmdsql = "SELECT uu" +"FROM login " +"WHERE " +"(usuario ='" + prodselect + "')";
            PreparedStatement stmt = conecta.prepareStatement(cmdsql);
            ResultSet rs = stmt.executeQuery();
            rs.first();
           
        } catch (Exception e) {
           // JOptionPane.showMessageDialog(this,"Usuário não tem permição para acessar ao menu");
        }
     */
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labeluser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labeperfil = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucaduser = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        cadusuario = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuproduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menurelatoriovenda = new javax.swing.JMenuItem();
        relatorioentrega = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Lanchonete");

        desktop.setToolTipText("");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user.png"))); // NOI18N
        jLabel4.setText("usuario:");

        labeluser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labeluser.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user.png"))); // NOI18N
        jLabel5.setText("Perfil:");

        labeperfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labeperfil.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeperfil)
                .addContainerGap(825, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeperfil)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labeluser)
                        .addComponent(jLabel4)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menucaduser.setText("Cadastros");

        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menucaduser.add(jMenuItem1);

        cadusuario.setText("Usuário");
        cadusuario.setEnabled(false);
        cadusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadusuarioActionPerformed(evt);
            }
        });
        menucaduser.add(cadusuario);

        jMenuItem3.setText("Entegrador");
        menucaduser.add(jMenuItem3);

        menuproduto.setText("Produto");
        menuproduto.setEnabled(false);
        menuproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuprodutoActionPerformed(evt);
            }
        });
        menucaduser.add(menuproduto);

        jMenuBar1.add(menucaduser);

        jMenu2.setText("Venda");

        jMenuItem4.setText("Nova Venda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Consultar Venda");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relátorios");

        menurelatoriovenda.setText("Venda de Produtos");
        menurelatoriovenda.setEnabled(false);
        jMenu3.add(menurelatoriovenda);

        relatorioentrega.setText("Entregas");
        relatorioentrega.setEnabled(false);
        jMenu3.add(relatorioentrega);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Pedidos");

        jMenuItem10.setText("Tela Pedidos");
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Tela Pedidos Finalizado");
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Opções");

        jMenuItem8.setText("Sair");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Logoff");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        desktop.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frmcliente telacliente = new Frmcliente();
        desktop.add(telacliente); 
         telacliente.setLocation(
                 desktop.getWidth() / 2 - telacliente.getWidth() / 2,
                 desktop.getHeight() / 2 - telacliente.getHeight() / 2
         );
         telacliente.setVisible(true);

                 
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cadusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadusuarioActionPerformed
     
   
        
        
        
        
        try {
            String cmdsql;

            cmdsql = "select * from login where usuario = '"+labeluser.getText()+"'";
            PreparedStatement stmt = conecta.prepareStatement(cmdsql);
            ResultSet rs = stmt.executeQuery();
            rs.first();
            if( rs.getString("perfil").equals("Administrador")){
               FrmCadusuario telauser = new FrmCadusuario();
          desktop.add(telauser); 
         telauser.setLocation(
                 desktop.getWidth() / 2 - telauser.getWidth() / 2,
                 desktop.getHeight() / 2 - telauser.getHeight() / 2);
          telauser.setVisible(true);   

            }
            else{
                JOptionPane.showMessageDialog(null,"Usuário não tem permição para acessar ao menu");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Usuário não tem permição para acessar ao menu");
        }

        

     

    }//GEN-LAST:event_cadusuarioActionPerformed

    private void menuprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuprodutoActionPerformed

                   Frmprodutos telaprodutos = new Frmprodutos();
                          desktop.add(telaprodutos); 
         telaprodutos.setLocation(
                 desktop.getWidth() / 2 - telaprodutos.getWidth() / 2,
                 desktop.getHeight() / 2 - telaprodutos.getHeight() / 2);
          telaprodutos.setVisible(true);      
      
                       
          

    }//GEN-LAST:event_menuprodutoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         FrmVendas telaprodutos = new FrmVendas();
                          desktop.add(telaprodutos); 
         telaprodutos.setLocation(
                 desktop.getWidth() / 2 - telaprodutos.getWidth() / 2,
                 desktop.getHeight() / 2 - telaprodutos.getHeight() / 2);
          telaprodutos.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
    Frmlogin telalogin = new Frmlogin();
    telalogin.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadusuario;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeluser;
    private javax.swing.JLabel labeperfil;
    private javax.swing.JMenu menucaduser;
    private javax.swing.JMenuItem menuproduto;
    private javax.swing.JMenuItem menurelatoriovenda;
    private javax.swing.JMenuItem relatorioentrega;
    // End of variables declaration//GEN-END:variables
}
